### ISSUE TITLE
Add schedule import to Google Calendar

### ISSUE THREAD

**Issue by Markusplay** [srkpi/sc-kpi-api#4]
Create a feature that allows users to import their group schedule into Google Calendar.
The endpoint should receive a group from the client, then we need to fetch the group's schedule from campus API `https://api.campus.kpi.ua/swagger/index.html` and import the schedule into Google Calendar.
The current version of this feature is `sr.kpi.ua/rozklad`. The issue with the current system is that it imports schedule on the two weeks at the start of the semester. New import should import correctly on the full semester

**Comment by yarman1** [comment]
The feature has the following flow:
1. The interface calls the authorization endpoint to obtain the necessary permissions.
2. The backend redirects to a special page of the interface, where the user can select needed pairs.
3. The interface sends the necessary json data.
